### ISSUE TITLE
Links to binaries for download is missing.

### ISSUE THREAD

**Issue by hmozaffari** [jqassistant-plugin/.github#2]
Hi, 
I'm not able to find links to binaries in new documentation structure. Where can I find 2.x binaries and download them?

**Comment by DirkMahler** [comment]
Assuming that you refer to jQA itself (not the plugins):

The command line utility can be downloaded from Maven Central, goto https://search.maven.org/search?q=a:jqassistant-commandline-distribution and select the `bin.zip` distribution from the `Download` menu on the right side.

For Maven it's specifying the jQA plugin:

```
            <plugin>
                <groupId>com.buschmais.jqassistant</groupId>
                <artifactId>jqassistant-maven-plugin</artifactId>
                <version>${jqassistant.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>scan</goal>
                            <goal>analyze</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Will update the docs with that information.
